### ISSUE TITLE
commercetools_category resource causes error

### ISSUE THREAD

**Issue by mikedebock** [labd/terraform-provider-commercetools#169]
When I try to create a category via the following definition, I get the following error: `Error: rpc error: code = Unavailable desc = transport is closing`
Using version: 0.29.0

Category definition:

```
resource "commercetools_category" "root-category" {
  key = "category-root"
  name = {
    en-US = "Categories"
    nl-NL = "Categorieën"
  }
  slug = {
    en-US = "category-root"
    nl-NL = "category-root"
  }
}
```

**Comment by davidweterings** [comment]
```2021-05-19T07:25:42.4689685Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: 2021/05/19 07:25:13 [DEBUG] Found following category:
2021-05-19T07:25:42.4691109Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: 2021/05/19 07:25:13 {
2021-05-19T07:25:42.4692340Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:     "version": 1,
2021-05-19T07:25:42.4693554Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:     "slug": {
2021-05-19T07:25:42.4695050Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:         "en-US": "category-aftikkers",
2021-05-19T07:25:42.4696470Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:         "nl-NL": "category-aftikkers"
2021-05-19T07:25:42.4697750Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:     },
2021-05-19T07:25:42.4699013Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:     "orderHint": "0.000016214091130231236041560",
2021-05-19T07:25:42.4700684Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:     "name": {
2021-05-19T07:25:42.4702046Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:         "en-US": "Aftikkers",
2021-05-19T07:25:42.4703809Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:         "nl-NL": "Aftikkers"
2021-05-19T07:25:42.4705144Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:     },
2021-05-19T07:25:42.4706700Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:     "lastModifiedBy": {
2021-05-19T07:25:42.4708183Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:         "clientId": "6HRO_jT9b29l1nj0ea1GtI3m"
2021-05-19T07:25:42.4709528Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:     },
2021-05-19T07:25:42.4710911Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:     "lastModifiedAt": "2021-05-19T07:25:13.025Z",
2021-05-19T07:25:42.4712563Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:     "key": "category-aftikkers",
2021-05-19T07:25:42.4714519Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:     "id": "56e09b58-174d-483c-94a6-640f44af34a6",
2021-05-19T07:25:42.4715992Z .terraform-provider-commercetools_v0.29.0:     "createdBy": {
2021-05-19T07:25:42.4717838Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:         "clientId": "6HRO_jT9b29l1nj0ea1GtI3m"
2021-05-19T07:25:42.4719442Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:     },
2021-05-19T07:25:42.4721723Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:     "createdAt": "2021-05-19T07:25:13.025Z",
2021-05-19T07:25:42.4723498Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0:     "ancestors": []
2021-05-19T07:25:42.4725127Z 2021-05-19T07:25:13.173Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: }
2021-05-19T07:25:42.4726382Z  runtime error: invalid memory address or nil pointer dereference
2021-05-19T07:25:42.4728005Z 2021-05-19T07:25:13.176Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe8fbf4]
2021-05-19T07:25:42.4729823Z 2021-05-19T07:25:13.176Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: 
2021-05-19T07:25:42.4731523Z 2021-05-19T07:25:13.176Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: goroutine 29 [running]:
2021-05-19T07:25:42.4734347Z 2021-05-19T07:25:13.176Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: github.com/labd/terraform-provider-commercetools/commercetools.resourceCategoryRead(0xc0001da2a0, 0x1192ca0, 0xc00041ee00, 0xf81420, 0x19004a8)
2021-05-19T07:25:42.4737433Z 2021-05-19T07:25:13.176Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: 	github.com/labd/terraform-provider-commercetools/commercetools/resource_category.go:227 +0x454
2021-05-19T07:25:42.4740501Z 2021-05-19T07:25:13.176Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: github.com/labd/terraform-provider-commercetools/commercetools.resourceCategoryCreate(0xc0001da2a0, 0x1192ca0, 0xc00041ee00, 0x2, 0x199b8c0)
2021-05-19T07:25:42.4743589Z 2021-05-19T07:25:13.176Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: 	github.com/labd/terraform-provider-commercetools/commercetools/resource_category.go:198 +0x690
2021-05-19T07:25:42.4746582Z 2021-05-19T07:25:13.176Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000438870, 0xc0001e4500, 0xc000317840, 0x1192ca0, 0xc00041ee00, 0xfec101, 0xc0001ecac8, 0xc0001f18c0)
2021-05-19T07:25:42.4749136Z 2021-05-19T07:25:13.177Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/resource.go:310 +0x375
2021-05-19T07:25:42.4752201Z 2021-05-19T07:25:13.177Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00010c980, 0xc0001ffa10, 0xc0001e4500, 0xc000317840, 0xc0001f3288, 0xc0003ceb80, 0xfede00)
2021-05-19T07:25:42.4754896Z 2021-05-19T07:25:13.177Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/provider.go:294 +0x99
2021-05-19T07:25:42.4757481Z 2021-05-19T07:25:13.177Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000ed20, 0x13300c0, 0xc0001e36b0, 0xc00041fce0, 0xc00000ed20, 0xc0001e36b0, 0xc000081b78)
2021-05-19T07:25:42.4760563Z 2021-05-19T07:25:13.177Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/helper/plugin/grpc_provider.go:885 +0x8ab
2021-05-19T07:25:42.4765334Z 2021-05-19T07:25:13.177Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1144840, 0xc00000ed20, 0x13300c0, 0xc0001e36b0, 0xc0001e8180, 0x0, 0x13300c0, 0xc0001e36b0, 0xc0001ea200, 0x1f7)
2021-05-19T07:25:42.4768812Z 2021-05-19T07:25:13.177Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
2021-05-19T07:25:42.4770959Z 2021-05-19T07:25:13.177Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00026a480, 0x1339820, 0xc00026b500, 0xc0000d0900, 0xc0002624e0, 0x195a780, 0x0, 0x0, 0x0)
2021-05-19T07:25:42.4773012Z 2021-05-19T07:25:13.177Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: 	google.golang.org/grpc@v1.27.1/server.go:1024 +0x522
2021-05-19T07:25:42.4775117Z 2021-05-19T07:25:13.177Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: google.golang.org/grpc.(*Server).handleStream(0xc00026a480, 0x1339820, 0xc00026b500, 0xc0000d0900, 0x0)
2021-05-19T07:25:42.4776994Z 2021-05-19T07:25:13.177Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: 	google.golang.org/grpc@v1.27.1/server.go:1313 +0xd34
2021-05-19T07:25:42.4778777Z 2021-05-19T07:25:13.177Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00032e110, 0xc00026a480, 0x1339820, 0xc00026b500, 0xc0000d0900)
2021-05-19T07:25:42.4780488Z 2021-05-19T07:25:13.177Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: 	google.golang.org/grpc@v1.27.1/server.go:722 +0xa5
2021-05-19T07:25:42.4782113Z 2021-05-19T07:25:13.177Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-05-19T07:25:42.4783731Z 2021-05-19T07:25:13.177Z [DEBUG] plugin.terraform-provider-commercetools_v0.29.0: 	google.golang.org/grpc@v1.27.1/server.go:720 +0xa5
2021-05-19T07:25:42.4786106Z 2021/05/19 07:25:13 [DEBUG] module.akeneo.commercetools_category.aftikkers: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021-05-19T07:25:42.4788282Z 2021-05-19T07:25:13.178Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-05-19T07:25:42.4790626Z 2021-05-19T07:25:13.178Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/labd/commercetools/0.29.0/linux_amd64/terraform-provider-commercetools_v0.29.0 pid=2098 error="exit status 2"```

**Comment by onur9** [comment]
This should be fixed by https://github.com/labd/terraform-provider-commercetools/pull/216 

I can add this category without an error.
