### ISSUE TITLE
Error: The terraform-provider-commercetools_v1.6.x.exe plugin crashed!

### ISSUE THREAD

**Issue by Incstar** [labd/terraform-provider-commercetools#340]
**Information**
Terraform version: 1.3.6 and 1.3.7 tested
Provider version: 1.6.3, 1.6.4, 1.6.5 and 1.6.6 tested 
Resource:   all commercetools ressources

**To Reproduce**
terraform init 
terraform plan

On terraform plan the terraform-provider-commercetools_v1.6.x.exe plugin crashed with multiple resources

The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.

LOGS: 
[terraform.txt](https://github.com/labd/terraform-provider-commercetools/files/10498536/terraform.txt)

**Comment by jahernandezmartinez13** [comment]
Happening the same here in OS X after upgrading to 1.6.6
```
╷
│ Error: Request cancelled
│ 
│   with module.leep-inventory-update-client.commercetools_api_client.leep_service_api_key,
│   on modules/api-client-secret-manager/api-key.tf line 1, in resource "commercetools_api_client" "leep_service_api_key":
│    1: resource "commercetools_api_client" "leep_service_api_key" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.leep-inventory-weekly-client.commercetools_api_client.leep_service_api_key,
│   on modules/api-client-secret-manager/api-key.tf line 1, in resource "commercetools_api_client" "leep_service_api_key":
│    1: resource "commercetools_api_client" "leep_service_api_key" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-commercetools_v1.6.6 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 374 [running]:
github.com/labd/terraform-provider-commercetools/internal/resources/project.(*Project).setStateData(_, {{0x2, {0xc00081adc8, 0x17}}, {0x2, {0xc00081adf8, 0x17}}, {0x2, 0x22}, {0x2, ...}, ...})
        github.com/labd/terraform-provider-commercetools/internal/resources/project/model.go:131 +0x1d2
github.com/labd/terraform-provider-commercetools/internal/resources/project.(*ProjectResource).Read(0xc0000120a8, {0x1fead40, 0xc0005a5bc0}, {{{{0x1fef9a8, 0xc000808e40}, {0x1c43fe0, 0xc0002b39b0}}, {0x1ff14d0, 0xc00021be50}}, 0xc0000120d0, ...}, ...)
        github.com/labd/terraform-provider-commercetools/internal/resources/project/resource.go:336 +0x365
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc000227600, {0x1fead40, 0xc0005a5bc0}, 0xc0005a5cb0, 0xc000357408)
        github.com/hashicorp/terraform-plugin-framework@v1.0.1/internal/fwserver/server_readresource.go:97 +0x617
github.com/hashicorp/terraform-plugin-framework/internal/proto5server.(*Server).ReadResource(0xc000227600, {0x1fead40?, 0xc0005a5a70?}, 0xc000630a00)
        github.com/hashicorp/terraform-plugin-framework@v1.0.1/internal/proto5server/server_readresource.go:53 +0x27b
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0xc00043a990, 0xc00043a9f0, {0xc0004588e0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ReadResource.go:26 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000156000, {0x1fead40?, 0xc0005a5260?}, 0xc0002dc480)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1df14c0?, 0xc000156000}, {0x1fead40, 0xc0005a5260}, 0xc0003e20e0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000a8000, {0x1fefd00, 0xc0001024e0}, 0xc0009607e0, 0xc0001a6c30, 0x271beb0, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0000a8000, {0x1fefd00, 0xc0001024e0}, 0xc0009607e0, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-commercetools_v1.6.6 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by mvantellingen** [comment]
Can you attempt https://registry.terraform.io/providers/labd/commercetools/1.6.7 ? It might fix it (but need more info to know for sure)

**Comment by Incstar** [comment]
@mvantellingen you are faster than lightning.
We tested on macOS with the same result BUT 
upgrade to version 1.6.7 solved the issue for both windows and mac. 
Thank you.

**Comment by mvantellingen** [comment]
Good to hear!
