### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by zackpollard** [labd/terraform-provider-commercetools#344]
**Information**
Terraform version: 1.3.7
Provider version: 1.6.8
Resource: cart-discount

**To Reproduce**

1. Create a cart-discount with the following terraform code.

```hcl
resource "commercetools_cart_discount" "cart_discount" {
  key  = "cart-discount-key"
  name = {
    en = "Cart Discount Name"
  }
  description = {
    en = "Cart Discount Description"
  }
  value {
    type = "absolute"
    money {
      currency_code = "GBP"
      cent_amount   = "389"
    }
  }
  predicate = "custom.customType = \"MatchingType\""
  target {
    type      = "lineItems"
    predicate = "productType.key = \"key1\" or productType.key = \"key2\""
  }
  sort_order             = "0.5000001"
  is_active              = true
  requires_discount_code = false
  stacking_mode = "Stacking"
}
```
2. Terraform creates the resources
3. Terraform gets the resources to validate and write them into state
4. Terraform throws the following error
```
2023-02-13T11:47:27.5893279Z 2023-02-13T11:47:27.586Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: ----------------------------------------------------------------------
2023-02-13T11:47:27.5928949Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: panic: Unknown money type
2023-02-13T11:47:27.5930674Z [33m╷[0m[0m
2023-02-13T11:47:27.5931372Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: 
2023-02-13T11:47:27.5932190Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: goroutine 61 [running]:
2023-02-13T11:47:27.5933224Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: github.com/labd/terraform-provider-commercetools/commercetools.flattenTypedMoney(...)
2023-02-13T11:47:27.5934396Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: 	github.com/labd/terraform-provider-commercetools/commercetools/marshalling.go:39
2023-02-13T11:47:27.5935631Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: github.com/labd/terraform-provider-commercetools/commercetools.flattenCartDiscountValue({0x10d7620?, 0xc000670d50?})
2023-02-13T11:47:27.5937547Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: 	github.com/labd/terraform-provider-commercetools/commercetools/resource_cart_discount.go:488 +0x3f3
2023-02-13T11:47:27.5938917Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: github.com/labd/terraform-provider-commercetools/commercetools.resourceCartDiscountRead({0x13ea228, 0xc00011eae0}, 0xc000258a80, {0x123e1a0?, 0xc00011b6c8?})
2023-02-13T11:47:27.5940279Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: 	github.com/labd/terraform-provider-commercetools/commercetools/resource_cart_discount.go:314 +0x4a5
2023-02-13T11:47:27.5942426Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: github.com/labd/terraform-provider-commercetools/commercetools.resourceCartDiscountCreate({0x13ea228?, 0xc00011eae0}, 0x0?, {0x123e1a0?, 0xc00011b6c8})
2023-02-13T11:47:27.5943758Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: 	github.com/labd/terraform-provider-commercetools/commercetools/resource_cart_discount.go:296 +0xa6b
2023-02-13T11:47:27.5945234Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000330e00, {0x13ea260, 0xc0001a90e0}, 0xd?, {0x123e1a0, 0xc00011b6c8})
2023-02-13T11:47:27.5946404Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:707 +0x12e
2023-02-13T11:47:27.5947719Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000330e00, {0x13ea260, 0xc0001a90e0}, 0xc0003a1790, 0xc000258900, {0x123e1a0, 0xc00011b6c8})
2023-02-13T11:47:27.5948875Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:837 +0xa85
2023-02-13T11:47:27.5950135Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000119c8, {0x13ea260?, 0xc0001a8fc0?}, 0xc0001249b0)
2023-02-13T11:47:27.5951352Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
2023-02-13T11:47:27.5952705Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc0003a6cf0, 0xc0003a6d50, {0xc0003c6940, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
2023-02-13T11:47:27.5953998Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: 	github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
2023-02-13T11:47:27.5955269Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00048e000, {0x13ea260?, 0xc0001a8510?}, 0xc00033e070)
2023-02-13T11:47:27.5956438Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: 	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
2023-02-13T11:47:27.5958270Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x11f05a0?, 0xc00048e000}, {0x13ea260, 0xc0001a8510}, 0xc00033e000, 0x0)
2023-02-13T11:47:27.5959588Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: 	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
2023-02-13T11:47:27.5960944Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00020a1e0, {0x13ef1a0, 0xc0003e8000}, 0xc00028c120, 0xc00048c330, 0x1b16d80, 0x0)
2023-02-13T11:47:27.5961983Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: 	google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
2023-02-13T11:47:27.5963150Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: google.golang.org/grpc.(*Server).handleStream(0xc00020a1e0, {0x13ef1a0, 0xc0003e8000}, 0xc00028c120, 0x0)
2023-02-13T11:47:27.5964135Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: 	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
2023-02-13T11:47:27.5965060Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: google.golang.org/grpc.(*Server).serveStreams.func1.2()
2023-02-13T11:47:27.5966015Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: 	google.golang.org/grpc@v1.51.0/server.go:965 +0x98
2023-02-13T11:47:27.5966954Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: created by google.golang.org/grpc.(*Server).serveStreams.func1
2023-02-13T11:47:27.5968152Z 2023-02-13T11:47:27.590Z [DEBUG] provider.terraform-provider-commercetools_v1.6.8: 	google.golang.org/grpc@v1.51.0/server.go:963 +0x28a
2023-02-13T11:47:27.5969290Z 2023-02-13T11:47:27.590Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/labd/commercetools/1.6.8/linux_amd64/terraform-provider-commercetools_v1.6.8 pid=386 error="exit status 2"
2023-02-13T11:47:27.5976379Z 2023-02-13T11:47:27.590Z [ERROR] plugin.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Canceled desc = context canceled"
2023-02-13T11:47:27.5977316Z 2023-02-13T11:47:27.591Z [ERROR] vertex "commercetools_cart_discount.moonpig_plus_first_purchase_discount_free_postage" error: Request cancelled
2023-02-13T11:47:27.5978456Z 2023-02-13T11:47:27.591Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Canceled desc = context canceled"
2023-02-13T11:47:27.5979542Z 2023-02-13T11:47:27.591Z [ERROR] plugin.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Canceled desc = context canceled"
2023-02-13T11:47:27.5980366Z 2023-02-13T11:47:27.591Z [ERROR] vertex "commercetools_cart_discount.moonpig_plus_card_discount" error: Request cancelled
2023-02-13T11:47:27.5981176Z 2023-02-13T11:47:27.591Z [ERROR] plugin.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Canceled desc = context canceled"
2023-02-13T11:47:27.5982026Z 2023-02-13T11:47:27.591Z [ERROR] vertex "commercetools_cart_discount.moonpig_plus_first_purchase_discount_free_card" error: Request cancelled
```

The error `panic: Unknown money type` comes from the provider directly, and appears to indicate that the type coming back from the SDK for the Money object isn't one that is known by the provider. Looking at the responses coming back from commercetools, the SDK should be matching this correctly. The `value` field of the cart discount came back as follows `"value":{"type":"absolute","money":[{"type":"centPrecision","currencyCode":"GBP","centAmount":389,"fractionDigits":2}]}` which looks like it should work based on the code in the SDK.

This is currently blocking us from using the commercetools provider for our use case of managing discounts for part of the project. Any indication of what is going on here would be great.

**Comment by m89724** [comment]
I am also facing same issue. Is there any update on this bug?

**Comment by zackpollard** [comment]
This issue still exists on version 1.6.9

**Comment by zackpollard** [comment]
Got some time to do a little investigation into this today. All of the acceptance tests for cart discounts use the relative value type with a permyriad instead of a money object. When switching these to use the absolute type with a money object, this error can be reproduced. I'm not a golang developer so muddling through this is pretty slow for me, however it seems like in flattenTypedMoney it is expecting either platform.HighPrecisionMoney/Money/CentPrecisionMoney. This however appears to be an array at this point, causing it to fall out of the switch and panic with "Unknown money type". I tried changing this code to accept an array just to see if that worked, but it appears there may even be further issues past just this one as I then get a terraform plugin sdk panic due to the returned value not being an array or slice, but a map. Any help with this would be appreciated, as it appears any cart discount that uses a value with a money type completely blows up the provider, however it is created correctly in commercetools.

**Comment by zackpollard** [comment]
Hey again, have seen there was a recent release so wondering if there was any possibility someone was able to look into this issue. Right now we have half of our discounts managed in terraform (anything percentage based) and everything else has to be added directly in the merchant centre which isn't ideal. @okkevandereijk Apologies for directly pinging you, I just saw that you recently replied on another issue. Would you be able to just comment if this is something that will be able to be looked into? If not we can try to set some time aside to look into it within our team, but none of us really have any golang experience so it's a bit of a rabbit hole for us as you can see with my previous comment 😆
