### ISSUE TITLE
Terraformer Error "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by markus-mw** [labd/terraform-provider-commercetools#358]
**Information**
Terraform version: v1.4.4
Provider version: v1.6.9
Resource: product_type
Terraformer version: v0.8.22

**To Reproduce**
Install terraformer and try to execute thefollowing command.

```shell
terraformer plan commercetools -r=product_type
```
Results in the following error:
```shell
2023-04-06T13:51:13.107+0200 [ERROR] plugin.terraform-provider-commercetools_v1.6.9.exe: Response contains error diagnostic: @module=sdk.proto
  diagnostic_detail=
  | An unexpected error was encountered trying to build a value. This is always an error in the provider. Please report the following to the provider developer:
  |
  | Received null value, however the target type cannot handle null values. Use the corresponding `types` package type, a pointer type or a custom type that handles null values.
  |
  | Path:
  | Target Type: provider.ctProviderModel
  | Suggested `types` Type: basetypes.ObjectValue
  | Suggested Pointer Type: *provider.ctProviderModel
   diagnostic_severity=ERROR tf_provider_addr=registry.terraform.io/labd/commercetools tf_rpc=Configure @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/diag/diagnostics.go:55 diag
nostic_attribute="" diagnostic_summary="Value Conversion Error" tf_proto_version=5.3 tf_req_id=1d7d3d3c-fd57-f2c2-ee2f-2aee8c56422f timestamp="2023-04-06T13:51:13.107+0200"
2023/04/06 13:51:13 commercetools importing... product_type
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x686ac4d]

goroutine 1 [running]:
github.com/labd/commercetools-go-sdk/commercetools.(*Client).doRequest(0x0, {0xb8343e0, 0xc0000b40f8}, {0xa7c1af7, 0x3}, {0xa7e8634?, 0x0?}, 0x0?, {0x0, 0x0}, ...)
        /home/runner/go/pkg/mod/github.com/labd/commercetools-go-sdk@v0.3.1/commercetools/client.go:224 +0x4d
github.com/labd/commercetools-go-sdk/commercetools.(*Client).query(...)
        /home/runner/go/pkg/mod/github.com/labd/commercetools-go-sdk@v0.3.1/commercetools/client.go:188
github.com/labd/commercetools-go-sdk/commercetools.(*Client).ProductTypeQuery(0xc001107318?, {0xb8343e0, 0xc0000b40f8}, 0xc0011072d0)
        /home/runner/go/pkg/mod/github.com/labd/commercetools-go-sdk@v0.3.1/commercetools/service_product_type.go:30 +0x136
github.com/GoogleCloudPlatform/terraformer/providers/commercetools.(*ProductTypeGenerator).InitResources(0xc0010e9c80)
        /home/runner/work/terraformer/terraformer/providers/commercetools/product_type.go:41 +0x32d
github.com/GoogleCloudPlatform/terraformer/cmd.initServiceResources({_, _}, {_, _}, {{0xc000aac1a0, 0x1, 0x1}, {0x11aec818, 0x0, 0x0}, ...}, ...)
        /home/runner/work/terraformer/terraformer/cmd/import.go:209 +0x21e
github.com/GoogleCloudPlatform/terraformer/cmd.initAllServicesResources(_, {{0xc000aac1a0, 0x1, 0x1}, {0x11aec818, 0x0, 0x0}, {0xa871034, 0x1e}, {0xa7d117c, ...}, ...}, ...)
        /home/runner/work/terraformer/terraformer/cmd/import.go:166 +0x1a7
github.com/GoogleCloudPlatform/terraformer/cmd.Import({_, _}, {{0xc000aac1a0, 0x1, 0x1}, {0x11aec818, 0x0, 0x0}, {0xa871034, 0x1e}, ...}, ...)
        /home/runner/work/terraformer/terraformer/cmd/import.go:98 +0x2a5
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdCommercetoolsImporter.func1(0xc001550000?, {0xa7c3340?, 0x1?, 0x1?})
        /home/runner/work/terraformer/terraformer/cmd/provider_cmd_commercetools.go:61 +0x2f2
github.com/spf13/cobra.(*Command).execute(0xc001550000, {0xc000aac170, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0012c9080)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute()
        /home/runner/work/terraformer/terraformer/cmd/root.go:36 +0x1e
main.main()
        /home/runner/work/terraformer/terraformer/main.go:39 +0x50

```

**Comment by demeyerthom** [comment]
Hi @markus-mw 

Could you maybe provide me with the terraform resource you are trying to execute the plan on? And is this an existing resource (so already in state) or a new one you are trying to add?

A nil pointer issue is not great, but I have too little info to pinpoint the issue
