### ISSUE TITLE
Subscription import fails on 1.6.9 version

### ISSUE THREAD

**Issue by aleksey-zvolinsky** [labd/terraform-provider-commercetools#360]
**Information**
Terraform version: 1.4.4
Provider version: 1.6.9
Resource: subscription

**To Reproduce**
1. Init and apply subscription - remember subscription-id
2. Remove state files
3. Import subscription using id from first step

```shell
terraform import commercetools_subscription.category-event-source <subscription-id>
```
Output
```shell
commercetools_subscription.category-event-source: Importing from ID "fb8d05a6-2ad3-454c-af78-6153eabacd32"...
commercetools_subscription.category-event-source: Import prepared!
  Prepared commercetools_subscription for import
commercetools_subscription.category-event-source: Refreshing state... [id=fb8d05a6-2ad3-454c-af78-6153eabacd32]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-commercetools_v1.6.9 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 102 [running]:
github.com/labd/terraform-provider-commercetools/internal/resources/subscription.(*Subscription).setSecretValues(...)
        github.com/labd/terraform-provider-commercetools/internal/resources/subscription/model.go:82
github.com/labd/terraform-provider-commercetools/internal/resources/subscription.(*subscriptionResource).Read(0x14000206698, {0x105117a20, 0x140006e45a0}, {{{{0x10511c5c8, 0x140006e5da0}, {0x104efca60, 0x140006e5a40}}, {0x10511e070, 0x14000219c20}}, 0x140002066a8, ...}, ...)
        github.com/labd/terraform-provider-commercetools/internal/resources/subscription/resource.go:338 +0x584
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0x14000227600, {0x105117a20, 0x140006e45a0}, 0x140006e4690, 0x140000cf3d0)
        github.com/hashicorp/terraform-plugin-framework@v1.0.1/internal/fwserver/server_readresource.go:97 +0x4b4
github.com/hashicorp/terraform-plugin-framework/internal/proto5server.(*Server).ReadResource(0x14000227600, {0x105117a20?, 0x140006e4450?}, 0x140004ed180)
        github.com/hashicorp/terraform-plugin-framework@v1.0.1/internal/proto5server/server_readresource.go:53 +0x1a4
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0x140004ba930, 0x140004ba990, {0x140004dc860, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ReadResource.go:26 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x1400014c140, {0x105117a20?, 0x140006d9a10?}, 0x14000120c00)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1050aab20?, 0x1400014c140}, {0x105117a20, 0x140006d9a10}, 0x14000449ab0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400028a000, {0x10511c920, 0x140000924e0}, 0x140006daa20, 0x14000193a40, 0x105826df0, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xb7c
google.golang.org/grpc.(*Server).handleStream(0x1400028a000, {0x10511c920, 0x140000924e0}, 0x140006daa20, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x290

Error: The terraform-provider-commercetools_v1.6.9 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

```hcl
terraform {
  required_providers {
    commercetools = {
      source = "labd/commercetools"
      version = "1.6.9"
    }
  }
}

resource "commercetools_subscription" "category-event-source" {
  key = "category-event-source"
  destination {
    type       = "EventBridge"
    account_id = 123456789012
    region     = "eu-west-1"
  }

  changes {
    resource_type_ids = ["category"]
  }
}

```

**Comment by karl18** [comment]
I've the same issue 
Information
Terraform version: 1.3.4
Provider version: 1.6.9
Resource: subscription

**Comment by demeyerthom** [comment]
Hi @aleksey-zvolinsky @karl18 looks like we were not handling the imports correctly for subscriptions. I will create a fix to address this!
