### ISSUE TITLE
commercetools_subscription "changes" block with multiple values for resource_type_ids causes an error

### ISSUE THREAD

**Issue by chawii** [labd/terraform-provider-commercetools#365]
**Information**
Terraform version: 1.2.8
Provider version: 1.5.1
Resource: commercetools_subscription

**To Reproduce**
1. terraform plan
2. terraform apply
3. Issue should be encountered

```hcl
# main.tf
terraform {
  required_providers {
    commercetools = {
      source  = "labd/commercetools"
      version = "1.5.1"
    }
  }
}

# subscription.tf
resource "commercetools_subscription" "sample_subscription" {
  key = "sample-subscription"
  destination {
    type       = "GoogleCloudPubSub"
    project_id = "project_id_here"
    topic      = "topic_name_here"
    region     = "region_here"
  }

  format {
    type                 = "CloudEvents"
    cloud_events_version = "1.0"
  }

  changes {
    resource_type_ids = ["product", "order"] # <----- Causes the issue
  }

  message {
    resource_type_id = "product"
    types = [
      "ProductCreated",
      "ProductPublished"
    ]
  }
}
```

Having more than one string array element for the changes.resource_type_ids causes this issue below:
```
commercetools_subscription.sample_subscription: Modifying... [id=17b3db7a-fc3f-4621-a3fb-16a097f423ae]
╷
│ Error: Plugin did not respond
│
│   with commercetools_subscription.sample_subscription,
│   on ct_subscription.tf line 1, in resource "commercetools_subscription" "sample_subscription":
│    1: resource "commercetools_subscription" "sample_subscription" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-commercetools_v1.5.1 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 47 [running]:
github.com/labd/terraform-provider-commercetools/commercetools.expandSubscriptionChanges(0x140006bae38?)
	github.com/labd/terraform-provider-commercetools/commercetools/resource_subscription.go:609 +0x1fc
github.com/labd/terraform-provider-commercetools/commercetools.resourceSubscriptionUpdate({0x10567eaa8?, 0x14000300780}, 0x14000262e80, {0x10565b420?, 0x1400011c3f0})
	github.com/labd/terraform-provider-commercetools/commercetools/resource_subscription.go:417 +0x540
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x14000500380, {0x10567eae0, 0x1400011ea50}, 0xd?, {0x10565b420, 0x1400011c3f0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:741 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000500380, {0x10567eae0, 0x1400011ea50}, 0x14000614f70, 0x14000263480, {0x10565b420, 0x1400011c3f0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:847 +0x67c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x140004c1f20, {0x10567ea38?, 0x1400057b880?}, 0x140006ac780)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1021 +0xb70
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x1400043c780, {0x10567eae0?, 0x14000643aa0?}, 0x140006b0620)
	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/tf5server/server.go:812 +0x384
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x105627cc0?, 0x1400043c780}, {0x10567eae0, 0x14000643aa0}, 0x140001aa720, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002a6a80, {0x105682658, 0x14000602340}, 0x1400029e000, 0x14000506d20, 0x105cbcfa0, 0x0)
	google.golang.org/grpc@v1.46.2/server.go:1283 +0xb50
google.golang.org/grpc.(*Server).handleStream(0x140002a6a80, {0x105682658, 0x14000602340}, 0x1400029e000, 0x0)
	google.golang.org/grpc@v1.46.2/server.go:1620 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.46.2/server.go:922 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.46.2/server.go:920 +0x290

Error: The terraform-provider-commercetools_v1.5.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by philippeckelintive** [comment]
@chawii  I'd suggest to use the latest provider version; see [here](https://github.com/labd/terraform-provider-commercetools/issues/366#issuecomment-1522929018) as well.

**Comment by chawii** [comment]
> @chawii I'd suggest to use the latest provider version; see [here](https://github.com/labd/terraform-provider-commercetools/issues/366#issuecomment-1522929018) as well.

@philippeckelintive confirmed that it's working with v1.6.9. Thank you, closing this as completed.
